# Check Insights/"Dependency graph" to make sure not errors exist in this file.
version: 2
updates:
  # Non-Python ecosystems which may also be of interest are Docker,
  # git submodules, and Terraform.
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
